baseURL = "http://localhost/"
title = "Gårdstorp, Öland"

languageCode = "sv-se"
DefaultContentLanguage = "se"

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true
paginate = 9
darkmode_js = ["assets/js/darkmode.js"]

enableInlineShortcodes = true

netlify = false
[params]
author = "Gårdstorp"
authorimage = "../assets/images/global/author.webp"
github = "https://github.com/01beacon"
og_image = "/images/tailbliss-cover.png"
sitename = "Välkommen till Gårdstorp, Öland"
description = "Hyr detta vackra hus"
hero_image = "images/pages/welcome-wrapper.jpeg"
section_image_1 = "images/pages/historisk-charm.jpg"
section_image_2 = "images/pages/room-beds.jpg"
section_image_3 = "images/pages/rum-baddar.jpg"
section_image_4 = "images/pages/komfort-bekvamlighet.jpg"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[taxonomies]
category = "Categories"
tag = "Tags"

[privacy]
[privacy.disqus]
disable = true
[privacy.googleAnalytics]
anonymizeIP = true
disable = false
respectDoNotTrack = false
useSessionStorage = false
[privacy.instagram]
disable = true
simple = false
[privacy.twitter]
disable = true
enableDNT = false
simple = false
[privacy.vimeo]
disable = true
enableDNT = false
simple = false
[privacy.youtube]
disable = true
privacyEnhanced = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.105.0"
    max = "0.105.0"
